user-id: 1
group-id: 1
memory-limit: 100Mi
volumes:
  /state: !Statedir {}
  /storage: !Persistent { path: /storage }
environ:
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8
  PYTHONIOENCODING: UTF-8
  PORT: 20000
  APP_CONFIG_FILE: /app/server/config/production.py
workdir: /app
executable: /usr/bin/python3
arguments:
  - manage.py
  - runprod
