before_script:
- vagga _init_storage_dir --allow-multiple banner-creator

stages:
- containers
- test
- cleanup

containers:
  stage: containers
  script:
  - vagga _build python

test:
  stage: test
  script:
  - vagga test

cleanup:
  stage: cleanup
  script:
  - vagga _clean --unused --at-least 1day
