"""empty message

Revision ID: 02dce9f010f3
Revises: 94643881b374
Create Date: 2016-07-21 18:24:56.486349

"""

# revision identifiers, used by Alembic.
revision = '02dce9f010f3'
down_revision = '94643881b374'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_image', sa.Integer(), nullable=False),
    sa.Column('json_hist', postgresql.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_image'], ['review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_history')
    ### end Alembic commands ###
