"""empty message

Revision ID: 0732a5782405
Revises: 6ddd40dc3e15
Create Date: 2016-08-16 14:14:26.030080

"""

# revision identifiers, used by Alembic.
revision = '0732a5782405'
down_revision = '6ddd40dc3e15'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('background_image', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('background_image', sa.Column('width', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('background_image', 'width')
    op.drop_column('background_image', 'height')
    ### end Alembic commands ###
