"""create headers

Revision ID: 40cde3c7eadb
Revises: 6ddd40dc3e15
Create Date: 2016-08-16 16:05:14.477752

"""

# revision identifiers, used by Alembic.
revision = '40cde3c7eadb'
down_revision = '6ddd40dc3e15'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('font_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['font_id'], ['font.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_header_project_id'), 'header', ['project_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_header_project_id'), table_name='header')
    op.drop_table('header')
    ### end Alembic commands ###
