"""empty message

Revision ID: 57efb7c54e86
Revises: 0732a5782405
Create Date: 2016-08-16 15:42:40.944452

"""

# revision identifiers, used by Alembic.
revision = '57efb7c54e86'
down_revision = '0732a5782405'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'banner', 'project', ['project_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'banner', type_='foreignkey')
    op.drop_column('banner', 'project_id')
    ### end Alembic commands ###
