"""Initial migration

Revision ID: 5baaa60f7a27
Revises: None
Create Date: 2016-07-13 16:24:15.176557

"""

# revision identifiers, used by Alembic.
revision = '5baaa60f7a27'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    ### end Alembic commands ###
