"""add user

Revision ID: 702ecf5e1369
Revises: 97726bebbb0f
Create Date: 2016-07-21 18:16:30.588239

"""

# revision identifiers, used by Alembic.
revision = '702ecf5e1369'
down_revision = '97726bebbb0f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_id', sa.String(length=255), nullable=True),
    sa.Column('social_type', sa.Enum('google', 'facebook', name='socialnetwork'), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('user', 'designer', 'admin', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index('ix_user_id_social_type', 'user', ['social_type', 'id'], unique=False)
    op.create_index(op.f('ix_user_social_id'), 'user', ['social_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_social_id'), table_name='user')
    op.drop_index('ix_user_id_social_type', table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
