"""JSON column for banner_review added

Revision ID: 71984638bfcf
Revises: 83aa90f15b01
Create Date: 2016-08-17 13:02:38.743130

"""

# revision identifiers, used by Alembic.
revision = '71984638bfcf'
down_revision = '83aa90f15b01'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner_review', sa.Column('comment_clouds', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner_review', 'comment_clouds')
    ### end Alembic commands ###
