"""Separate models for images. Add models for reviews and projects

Revision ID: 7a889cfdf144
Revises: fa490d2a7e4a
Create Date: 2016-07-30 19:31:46.043477

"""

# revision identifiers, used by Alembic.
revision = '7a889cfdf144'
down_revision = 'fa490d2a7e4a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('background_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('preview', sa.String(length=64), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('preview')
    )
    op.create_table('banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('preview', sa.String(length=64), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('preview')
    )
    op.create_table('banner_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banner_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('accepted', 'not_accepted', name='status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('designer_comment', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('designer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['banner_id'], ['banner.id'], ),
    sa.ForeignKeyConstraint(['designer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('image', sa.Column('description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'description')
    op.drop_table('banner_review')
    op.drop_table('banner')
    op.drop_table('background_image')
    op.drop_table('project')
    ### end Alembic commands ###
