"""add button to project

Revision ID: 83aa90f15b01
Revises: 155c90535909
Create Date: 2016-08-17 16:20:11.627246

"""

# revision identifiers, used by Alembic.
revision = '83aa90f15b01'
down_revision = '155c90535909'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('button', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'project', ['button'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_column('project', 'button')
    ### end Alembic commands ###
