"""empty message

Revision ID: 96e2da0c9847
Revises: 03b09c3d91cb
Create Date: 2016-08-11 08:49:47.596702

"""

# revision identifiers, used by Alembic.
revision = '96e2da0c9847'
down_revision = '03b09c3d91cb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner_review', sa.Column('comment_clouds', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner_review', 'comment_clouds')
    ### end Alembic commands ###
