"""empty message

Revision ID: 9fe87ed17d0d
Revises: 5baaa60f7a27
Create Date: 2016-07-14 15:44:24.327488

"""

# revision identifiers, used by Alembic.
revision = '9fe87ed17d0d'
down_revision = '5baaa60f7a27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('active', sa.BOOLEAN(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'active')
    ### end Alembic commands ###
