"""add readable name to font

Revision ID: b851c858aac8
Revises: 71984638bfcf
Create Date: 2016-08-20 21:12:02.097575

"""

# revision identifiers, used by Alembic.
revision = 'b851c858aac8'
down_revision = '71984638bfcf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('font', sa.Column('readable_name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('font', 'readable_name')
    ### end Alembic commands ###
