"""removed token in user

Revision ID: b8f0a14b63a1
Revises: cd3bb93cc4e6
Create Date: 2016-07-19 18:10:53.164637

"""

# revision identifiers, used by Alembic.
revision = 'b8f0a14b63a1'
down_revision = 'cd3bb93cc4e6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.create_index('ix_user_id_social_type', 'user', ['social_type', 'id'], unique=False)
    op.drop_index('ix_user_token', table_name='user')
    op.drop_index('ix_user_token_social_type', table_name='user')
    op.drop_column('user', 'l_name')
    op.drop_column('user', 'f_name')
    op.drop_column('user', 'token')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('f_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('l_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_user_token_social_type', 'user', ['social_type', 'token'], unique=False)
    op.create_index('ix_user_token', 'user', ['token'], unique=False)
    op.drop_index('ix_user_id_social_type', table_name='user')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    ### end Alembic commands ###
