"""empty message

Revision ID: c9a71973ec35
Revises: 7a889cfdf144
Create Date: 2016-08-01 16:55:02.129527

"""

# revision identifiers, used by Alembic.
revision = 'c9a71973ec35'
down_revision = '7a889cfdf144'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_constraint('image_history_review_image_fkey', 'image_history', type_='foreignkey')
    op.create_foreign_key(None, 'image_history', 'banner', ['review_image'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image_history', type_='foreignkey')
    op.create_foreign_key('image_history_review_image_fkey', 'image_history', 'review', ['review_image'], ['id'])
    op.create_table('review',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status_review', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='review_pkey'),
    sa.UniqueConstraint('name', name='review_name_key')
    )
    ### end Alembic commands ###
