"""empty message

Revision ID: cc9b78ad9842
Revises: c9a71973ec35
Create Date: 2016-08-02 18:46:47.769330

"""

# revision identifiers, used by Alembic.
revision = 'cc9b78ad9842'
down_revision = 'c9a71973ec35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner_review', sa.Column('designer_reviewed', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'banner_review', ['designer_reviewed'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'banner_review', type_='unique')
    op.drop_column('banner_review', 'designer_reviewed')
    ### end Alembic commands ###
