"""simplify user

Revision ID: d1ae75688df7
Revises: 702ecf5e1369
Create Date: 2016-07-22 12:32:16.769296

"""

# revision identifiers, used by Alembic.
revision = 'd1ae75688df7'
down_revision = '702ecf5e1369'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'gender',
               existing_type=postgresql.ENUM('male', 'female', name='gender'),
               nullable=True)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_social_id', table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_social_id', 'user', ['social_id'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.alter_column('user', 'gender',
               existing_type=postgresql.ENUM('male', 'female', name='gender'),
               nullable=False)
    ### end Alembic commands ###
