"""added status to user

Revision ID: fa490d2a7e4a
Revises: 702ecf5e1369
Create Date: 2016-07-27 18:48:16.458165

"""

# revision identifiers, used by Alembic.
revision = 'fa490d2a7e4a'
down_revision = '702ecf5e1369'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.BOOLEAN(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    ### end Alembic commands ###
